spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Defi_Blockchain;encrypt=false
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.docker.compose.enabled=false